export const REGISTER = 'REGISTER';
export const SEARCH_RESULT = 'SEARCH_RESULT';
export const GET_CURRENT_EXAMINATION = 'GET_CURRENT_EXAMINATION';
export const GET_ALL_EXAMINATION = 'GET_ALL_EXAMINATION';
export const GET_ALL_ROOM_OF_EXAMINATION = 'GET_ALL_ROOM_OF_EXAMINATION';
export const GET_ALL_CANDIDATE_OF_ROOM_OF_EXAMINATION = 'GET_ALL_CANDIDATE_OF_ROOM_OF_EXAMINATION';
export const GET_ALL_ROOM_OF_EXAMINATION_AND_LEVEL = 'GET_ALL_ROOM_OF_EXAMINATION_AND_LEVEL';