build:
	docker build -t ftpl_backend .

up:
	docker-compose -p english_center up

down:
	docker-compose -p english_center down

restart:
	docker-compose -p english_center down
	docker-compose -p english_center up