build:
	docker build -t ftpl_frontend .

up:
	docker-compose -p english_center_fe up

down:
	docker-compose -p english_center_fe down

restart:
	docker-compose -p english_center_fe down
	docker-compose -p english_center_fe up